accounts/urls.py
from django.urls import path

from accounts.views import login_view, register_view, logout_view


urlpatterns = [
    path('login', login_view, name='login'),
    path('register', register_view, name='register'), 
    path('logout', logout_view, name='logout'), 
] 

app/urls.py
from django.urls import path

from app.views import home_views, contact_views, about_views

app_name = 'app'

urlpatterns = [
    path('', home_views, name='home'),
    path('contact', contact_views, name='contact'),
    path('about', about_views, name='about')
]

entreprise/urls.py
from django.urls import path

from entreprise.views import entreprise_home

app_name = 'entreprise'

urlpatterns = [
    path('', entreprise_home, name='entreprise_home'),
]

es/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('particulier/', include('particulier.urls')),
    path('entreprise/', include('entreprise.urls')),
    path('ourteam/', include('ourteam.urls')),
    path('admin/', admin.site.urls),
]

handler400 = 'handlers.views.handler400'
handler403 = 'handlers.views.handler403'
handler404 = 'handlers.views.handler404'
handler500 = 'handlers.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ourteam/urls.py
from django.urls import path

from ourteam.views import about_view, team_view

app_name = 'ourteam'
urlpatterns = [
    path('', about_view, name='about'),
    path('ourteam/<team_id>', team_view, name='team'),
]

particulier/urls.py
from django.urls import path

from particulier.views import particulier_views

app_name = 'particulier'

urlpatterns = [
    path('', particulier_views, name='particulier_home')
]

accounts/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models

# Create your models here.

entreprise/models.py
from django.db import models

# Create your models here.

handlers/models.py
from django.db import models

# Create your models here.

ourteam/models.py
from django.db import models

# Create your models here.
class OurTeam(models.Model):
    team_name = models.CharField(max_length=55)
    team_designation = models.CharField(max_length=55)
    team_description = models.TextField()
    team_image = models.ImageField(upload_to='team_img/')
    # team_social = models.ForeignKey(ReseauSociaux, on_delete=models.CASCADE)
    team_facebook = models.URLField()
    team_twitter = models.URLField()
    team_linkedIn = models.URLField()
    team_instagram = models.URLField()
    team_youtube = models.URLField()
    team_created_date = models.DateTimeField(auto_now_add=True)
    team_updated_date = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('ourteam:team', args=[str(self.id)])

    def __str__(self):
        return self.team_name

particulier/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User

# Create your views here.

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, "Vous êtes maintenant authentifié!")
            return redirect('sondage:sondage')
        else:
            messages.error(request, "les informations d'identification invalides, vérifier votre prénom")
            return redirect('login')
    return render(request, 'pages/accounts/login.html')


def register_view(request):
    if request.method == 'POST':
        # Get form vales
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        # Check if passwords match
        if password == password2:
            # Check username
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Ce Nom d\'utilisateur est déjà pris')
                return redirect('acounts:register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, 'Cette email est déjà utilisé!')
                    return redirect('register')
                else:
                    #Looks good
                    user = User.objects.create_user(username=username, password=password, email=email, first_name=first_name, last_name=last_name)
                    #Login after register
                    # auth.login(request, user)
                    # messages.success(request, "You are now loged in")
                    # return redirect('index')

                    user.save()
                    messages.success(request, 'Congratulations! Vous êtes maintenant enregistrée! Veillez à present vous connecter')
                    return redirect('login')
        else:
            messages.error(request, 'le mot de passe ne corresponds pas')
            return redirect('register')
    else:
        print("False")
        return render(request, 'pages/accounts/register.html')
    

    return render(request, 'pages/accounts/register.html')

def logout_view(request):
    if request.method == 'GET':
        auth.logout(request)
        messages.success(request, "Vous êtes déconnecté.")
        return redirect('login')
    else:
        return redirect('actualite:actualite')

app/views.py
from django.shortcuts import render

# Create your views here.
def home_views(request):
    template_name = 'pages/app/home.html'
    return render(request, template_name, context=None)

def contact_views(request):
    template_name = 'pages/app/contact.html'
    return render(request, template_name, context=None)

def about_views(request):
    template_name = 'pages/app/about.html'
    return render(request, template_name, context=None)

entreprise/views.py
from django.shortcuts import render

# Create your views here.

def entreprise_home(request):
    template_name = 'pages/entreprise/entreprise_home.html'
    context = None
    return render(request, template_name, context)

handlers/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.views.defaults import page_not_found
# Create your views here.
#Bad request
def handler400(request, exception):
	return render(request,  template_name='error/400.html')
	response.status_code = 400
	return response

#Permission denied
def handler403(request, exception):
	return render(request,  template_name='error/403.html')
	response.status_code = 403
	return response

#Page not found
def handler404(request, exception):
	return render(request,  template_name='error/404.html')
	response.status_code = 404
	return response

#Server error
def handler500(request):
	return render(request,  template_name='error/500.html')
	response.status_code = 500
	return response

ourteam/views.py
from django.shortcuts import render

from ourteam.models import OurTeam

# Create your views here.
def about_view(request):
    team_list = OurTeam.objects.all()
    context = {
        'team_list': team_list
    }
    template_name = 'pages/ourteam/about.html'
    return render(request, template_name, context)


def team_view(request, team_id):
    team = OurTeam.objects.get(id = team_id)
    context = {
        'team': team
    }
    template_name = 'pages/ourteam/team.html'
    return render(request, template_name, context)

particulier/views.py
from django.shortcuts import render

# Create your views here.
def particulier_views(request):
    template_name = 'particulier/particulier_home.html'
    context = {}
    return render(request, template_name, context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="icon" href="{% static 'img/logo-transparent.png'%}" type="image/png">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
    <link rel="stylesheet" href="{% static 'css/team.css' %}">
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/error.css' %}">
    <link rel="stylesheet" href="{% static 'css/contact.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/4b9ba14b0f.js" crossorigin="anonymous"></script>
</head>
<body>

    {% block content %}{% endblock content %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/entreprise.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Entreprise {% endblock %}
{% block content %}

{% include 'nav/toolbar.html' %}

{% block entreprise %}{% endblock entreprise %}

{% include 'nav/footer.html' %}

{% endblock content %}

templates/nav/footer.html
<footer class="container-fluid">
    <div class="row py-5">
        <div class="order-3 col-12 order-lg-1 col-lg-4 social-and-copyright text-center footer-col">
            <div class="text-center">
                <!-- <ul class="list-unstyled nav-links text-white text-left">
                    <li>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-house-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M8 3.293l6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                            <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
                        </svg>
                        <span class="pl-2">
                            343, Bld Lumumba, 11ème Rue Limete Industrielle, Réf. 
                                Congrégation CICM Kinshasa. RD. Congo.
                        </span>
                    </li>
                    <li>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-envelope-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z"/>
                        </svg>
                        <span class="pl-2">
                           ccnsc@ccnsc-rdc.org 
                        </span>
                    </li>
                    <li>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-telephone-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M2.267.98a1.636 1.636 0 0 1 2.448.152l1.681 2.162c.309.396.418.913.296 1.4l-.513 2.053a.636.636 0 0 0 .167.604L8.65 9.654a.636.636 0 0 0 .604.167l2.052-.513a1.636 1.636 0 0 1 1.401.296l2.162 1.681c.777.604.849 1.753.153 2.448l-.97.97c-.693.693-1.73.998-2.697.658a17.47 17.47 0 0 1-6.571-4.144A17.47 17.47 0 0 1 .639 4.646c-.34-.967-.035-2.004.658-2.698l.97-.969z"/>
                        </svg>
                        <span class="pl-2">
                          +243 82 117 8568  
                        </span>
                    </li>
                    <li>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-phone-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M3 2a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V2zm6 11a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                        </svg>
                        <span class="pl-2">
                           +243 99 992 9705 
                        </span>
                    </li>
                </ul> -->              
            </div>
            <div class="text-center pt-3">
                <ul class="list-inline">
                    <li class="d-inline pr-2"><a href="https://www.facebook.com/" target="_blank" class="text-white"><i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i></a></li>
                    <li class="d-inline pr-2"><a href="https://twitter.com/" target="_blank" class="text-white"><i class="fa fa-twitter fa-2x" aria-hidden="true"></i></a></li>
                    <li class="d-inline pr-2"><a href="https://www.instagram.com/" target="_blank" class="text-white"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a></li>
                    <li class="d-inline pr-2"><a href="https://linkedin.com/" target="_blank" class="text-white"><i class="fa fa-linkedin fa-2x" aria-hidden="true"></i></a></li>
                    <li class="d-inline pr-2"><a href="https://youtube.com/" target="_blank" class="text-white"><i class="fa fa-youtube fa-2x" aria-hidden="true"></i></a></li>
                </ul>
                <p>&copy; 2020 - Eventdrc Technology & EIC</p>
            </div>
        </div>
        <div class="order-1 col-12 col-md-6 order-lg-2 col-lg-4 footer-col m-2 m-sm-0">
            <div class="text-center">
                <h4 class="text-white">Menu</h4>
                <ul class="list-unstyled nav-links text-white">
                    <li><a href="{% url 'app:home' %}" class="footer-link text-white">Acceuil</a></li>
                    <li><a href="{% url 'app:contact' %}" class="footer-link text-white">Contact</a></li>
                    <li><a href="{% url 'ourteam:about' %}" class="footer-link text-white">A Propos de CCNSC-RDC</a></li>
                    <li><a href="{% url 'login' %}" class="footer-link text-white">Mon compte</a></li>
                </ul>
            </div>
            <hr class="footer-hr d-block d-md-none mx-auto">
        </div>
        <div class="order-2 col-12 col-md-6 col-lg-4 footer-col mb-2 mb-sm-0">
            <div class="text-center pb-3">
                <h4 class="text-white">Temps d'ouverture</h4>
                <ul class="list-unstyled nav-links text-white">
                    <li><i class="fa fa-clock"></i>&nbsp;&nbsp;Lundi du Vendredi : 08:30 - 16:30</li>
                    <li><i class="fa fa-clock"></i>&nbsp;&nbsp;Samedi: 08:30 - 13:00</li>
                </ul>
            </div>
            <hr class="footer-hr d-block d-md-none mx-auto">
            <!-- <div class="text-center newsletter">
                <h4 class="text-white">Newsletter</h4>
                <p class="text-white ">Restez informer en temps réel en souscrivant</p>
                <div class="txtb">
                    <input type="email" placeholder="Enter Your Email Address">
                    <button type="button"><i class="fa fa-search"></i></i></button>
                </div>
            </div> -->
            <div class="text-center pb-3">
                <!-- <h4 class="text-white">Newsletter</h4>
                <form enctype="multipart/form-data" method="post" action="/newsletter/newsletter/subscribe/">
                    {% csrf_token %}
                    <label for="id_email_field">E-mail:</label>
                    <input type="email" name="email_field" required="" id="id_email_field" placeholder="Email">
                    <button id="id_submit" name="submit" value="Subscribe" type="submit">Abonnez-vous</button>
                </form> -->
            </div>
        </div>
    </div>
</footer>

templates/nav/toolbar.html
{% load static %}

<nav class="navbar sticky-top navbar-expand-lg sticky-top navbar-dark shadow" style="background-color: #0c7880;">
  <a class="navbar-brand" href="{% url 'app:home' %}">
      <img class="nav-logo" src="{% static 'img/logo-transparent.png' %}" style="width: 50px; height: 50px;" alt="CCNSC-RDC"/>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    {% with request.resolver_match.url_name as url_name %}
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if url_name == 'home' %}active{% endif %}">
          <a class="nav-link" href="{% url 'app:home' %}">Acceuil</a>
        </li>
        <li class="nav-item {% if url_name == 'about' %}active{% endif %}">
          <a class="nav-link" href="{% url 'ourteam:about' %}">A Propos de Nous</a>
        </li>
        <li class="nav-item {% if url_name == 'contact' %}active{% endif %}">
          <a class="nav-link" href="{% url 'app:contact' %}">Contact</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        {% if not request.user.is_authenticated %}
          <li class="nav-item {% if url_name == 'login' %}active{% endif %}">
            <a class="nav-link" href="{% url 'login' %}">Se connecter</a>
          </li>
          <li class="nav-item {% if url_name == 'register' %}active{% endif %}">
            <a class="nav-link" href="{% url 'register' %}">Créez un compte</a>
          </li>
        {% else %}
          <li class="nav-item {% if url_name == 'logout' %}active{% endif %}">
            <a class="nav-link" href="{% url 'logout' %}">Déconnexion</a>
          </li>
        {% endif %}
      </ul>
    {% endwith %}
  </div>
</nav>

templates/notifications/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error:
                    {% else %}
                        {{ message.tags|title }}
                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/pages/accounts/login.html
{% extends 'sousbase.html' %}
{% load static %}
{% block sousbase %}

<section id="login" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white login__label">
              <h4><i class="fa fa-sign-in fa-2x" aria-hidden="true"></i> Se Connecter</h4>
            </div>
            <div class="card-body pb-0">
                <!-- Alerts -->
                {% include 'notifications/_alerts.html' %}
                <form action="{% url 'login' %}" method="POST">
                    {% csrf_token %}
                <div class="form-group">
                  <label for="username">Prénom</label>
                  <input type="text" name="username" class="form-control" required>
                </div>

                <div class="form-group">
                  <label for="password2">Mot de passe</label>
                  <input type="password" name="password" class="form-control" required>
                </div>

                <input type="submit" value="Se Connecter " class="btn btn-secondary btn-block login__btn">
                <div class="login__notreg">
                  <span>Pas encore de compte?</span>
                  <a class="text-right" href="{% url 'register' %}">S'enregister</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</section>

{% endblock %}

templates/pages/accounts/register.html
{% extends 'sousbase.html' %}
{% load static %}

{% block sousbase %}

<section id="register" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white login__label">
              <h4><i class="fa fa-user-plus fa-2x" aria-hidden="true"></i> Inscriptions</h4>
            </div>
            <div class="card-body pb-0">
                <!-- Alerts -->
                {% include 'notifications/_alerts.html' %}
                <form action="{% url 'register' %}" method="POST">
                    {% csrf_token %}
                  <div class="form-group">
                  <label for="first_name">Nom</label>
                  <input type="text" name="first_name" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="last_name">Post-Nom</label>
                  <input type="text" name="last_name" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="username">Prénom</label>
                  <input type="text" name="username" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="email">Email</label>
                  <input type="email" name="email" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="password2">Mot de passe</label>
                  <input type="password" name="password" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="password">Répéter votre mot de passe</label>
                  <input type="password" name="password2" class="form-control" required>
                </div>
                <input type="submit" value="S'enregister" class="btn btn-secondary btn-block login__btn">
                <div class="login__notreg">
                  <span>Avez-vous déjà un compte?</span>
                  <a class="text-right" href="{% url 'login' %}">Se connecter</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

templates/pages/app/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Acceuil {% endblock title %}

{% block content %}

    <div class="hero" style="background-image: url({% static 'img/background.png' %})">
        <div class="header">
            <img src="{% static 'img/logo-transparent.png' %}" class="logo" alt="Entreprise Solutions">
            {% with request.resolver_match.url_name as url_name %}
                <div class="dropdown">
                    <button class="btn dropdown-toggle auth" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <svg width="5em" height="1em" viewBox="0 0 16 16" class="bi bi-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                        </svg>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item {% if url_name == 'app:home' %}active{% endif %}" href="#">Tableau de bord</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item {% if url_name == 'logout' %}active{% endif %}" href="{% url 'logout' %}">Déconnexion</a>
                        {% else %}
                            <a class="dropdown-item {% if url_name == 'login' %}active{% endif %}" href="{% url 'login' %}">Connexion</a>
                            <a class="dropdown-item {% if url_name == 'register' %}active{% endif %}" href="{% url 'register' %}">Inscription</a>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item {% if url_name == 'contact' %}active{% endif %}" href="{% url 'app:contact' %}">Contact</a>
                        <a class="dropdown-item {% if url_name == 'about' %}active{% endif %}" href="{% url 'ourteam:about' %}">
                            A Propos de Nous!
                        </a>
                    </div>
                </div>
            {% endwith %}
        </div>
        <div class="content">
            <h4>
                Bienvenue sur 
                <br> <span class="entreprise">Entreprise</span> <span class="particulier">Solutions</span>  
                <br> Trouvez ce dont vous avez besoin
            </h4>

            <button type="button" class="btn-content"><a href="{% url 'entreprise:entreprise_home'%}">Entreprise</a></button>
            <button type="button" class="btn-content"><a href="{% url 'particulier:particulier_home'%}">Particulier</a></button>
        </div>

        <div class="bubbles">
            <img src="{% static 'img/bubble.png' %}" class="logo" alt="Entreprise Solutions">
            <img src="{% static 'img/bubble.png' %}" class="logo" alt="Entreprise Solutions">
            <img src="{% static 'img/bubble.png' %}" class="logo" alt="Entreprise Solutions">
            <img src="{% static 'img/bubble.png' %}" class="logo" alt="Entreprise Solutions">
            <img src="{% static 'img/bubble.png' %}" class="logo" alt="Entreprise Solutions">
            <img src="{% static 'img/bubble.png' %}" class="logo" alt="Entreprise Solutions">
            <img src="{% static 'img/bubble.png' %}" class="logo" alt="Entreprise Solutions">
        </div>

        <!-- <div class="bottom-bar">
            <img src="{% static 'img/menu.png' %}" class="menu" alt="Entreprise Solutions">
            <div class="social-links">
                <img src="{% static 'img/fb.png' %}" alt="Entreprise Solutions">
                <img src="{% static 'img/ig.png' %}" alt="Entreprise Solutions">
                <img src="{% static 'img/tw.png' %}" alt="Entreprise Solutions">
            </div>
            <div class="useful-links">
                <img src="{% static 'img/share.png' %}" alt="Entreprise Solutions">
                <img src="{% static 'img/info.png' %}" alt="Entreprise Solutions">
            </div>
        </div> -->
    </div>

{% endblock content %}

templates/pages/entreprise/entreprise_home.html
{% extends 'entreprise.html' %}
{% load static %}
{% block entreprise %}



{% endblock entreprise %}

templates/pages/ourteam/about.html
{% extends 'sousbase.html' %}
{% load static %}
{% block title %}A Propos de Nous!{% endblock title %}

{% block sousbase %}

<div class="about my-4"> 
    <!-- <img src="{% static 'img/about.png' %}" class="w-100 h-20 pb-4" alt="A Propos de la  Cadre de Concertation Nationale de la Société Civile Congolaise"> -->

    <div class="container banner">       
        <h2>A Propos de Nous</h2>
    </div>


    <div class="wrapper">
        <h1>Notre coordination</h1>
        <div class="team">
            {% for team in team_list %}
                <div class="team_member shadow-lg">
                    <div class="team_img">
                        <img src="{{ team.team_image.url }}" alt="{{ team.team_name }}">
                    </div>
                    <h3><a href="{% url 'ourteam:team' team.id %}">{{ team.team_name|truncatechars:25 }}</a></h3>
                    <p class="role">{{ team.team_designation }}</p>
                    <p>
                       {{ team.team_description|truncatechars:100 }}
                    </p>
                </div>
            {% endfor %}
        </div>
    </div>	
</div>

{% endblock sousbase %}

templates/pages/particulier/particulier_home.html
{% extends 'particulier.html' %}
{% load static %}
{% block particulier %}



{% endblock particulier %}

templates/particulier.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Particulier {% endblock %}
{% block content %}

    {% include 'nav/toolbar.html' %}

    {% block particulier %}{% endblock particulier %}

    {% include 'nav/footer.html' %}

{% endblock content %}

templates/sousbase.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {% endblock %}
{% block content %}

    {% include 'nav/toolbar.html' %}

    {% block sousbase %}{% endblock sousbase %}
    
    {% include 'nav/footer.html' %}

{% endblock content %}